# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: paxos-web-service
spec:
  selector:
    app: paxos-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
