apiVersion: v1
kind: Service
metadata:
  name: paxos-service
spec:
  selector:
    app: paxos-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30419
